name: github-actions-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with: 
        dotnet-verison: 2.2.104
    - name: Install dependencies
      run: dotnet restore ./src/github.actions/github.actions
    - name: Build
      run: dotnet build ./src/github.actions/github.actions/github.actions.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/github.actions/github.actions.tests/github.actions.tests.csproj --no-restore --verbosity normal
    - name: typescript lint
      run: |
        npm install ./src/github.actions/github.actions/ClientApp
        cd ./src/github.actions/github.actions/ClientApp
        npm install angular
        npm run lint
    - name: npm build
      run: |
        cd ./src/github.actions/github.actions/ClientApp
        npm run build --env=prod
    - name: publish
      run: dotnet publish ./src/github.actions/github.actions/github.actions.csproj --output ./drop
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ./drop
